spin_manifest_version = "1"
authors = ["Huynh Duc Dung <dunghd.it@gmail.com>"]
description = "Simple Typescript App"
name = "spin-ts-demo"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-ts-demo"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
